[tool.black]
line-length = 100
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.idea
  | \.pycharm_helpers
  | \__pycache__
  | \.hg
  | \.mypy_cache
  | \.tox
  | \venv
  | \Site/media
  | \Site/static
  | _build
  | buck-out
  | build
  | dist
  | migrations
)/
'''
